name: .NET Build

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
          cache: true

      - name: Build Solution
        run: dotnet pubilsh -p:PublishProfile=FolderProfile

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: App
          path: ./bin/publish/*
